name: Tests

on:
  push:
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.prettierrc.json'
      - '.prettierrc.json'
      - 'LICENSE'
      - 'README.md'
      - 'install.sh'
      - 'laradumps.yaml'
      - 'screenshot.png'
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-install=dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install npm dependencies
        run: npm install --no-interactive

      - name: Build assets
        run: npm run build

      - name: Execute lint tests
        run: vendor/bin/pint --test

      - name: Execute unit/feature tests
        run: vendor/bin/pest --ci
